export const RECIPES_LIST_REQUEST = "RECIPES_LIST_REQUEST";
export const RECIPES_LIST_SUCCESS = "RECIPES_LIST_SUCCESS";
export const RECIPES_LIST_FAIL = "RECIPES_LIST_FAIL";

export const RECIPES_CREATE_REQUEST = "RECIPES_CREATE_REQUEST";
export const RECIPES_CREATE_SUCCESS = "RECIPES_CREATE_SUCCESS";
export const RECIPES_CREATE_FAIL = "RECIPES_CREATE_FAIL";

export const RECIPES_UPDATE_REQUEST = "RECIPES_UPDATE_REQUEST";
export const RECIPES_UPDATE_SUCCESS = "RECIPES_UPDATE_SUCCESS";
export const RECIPES_UPDATE_FAIL = "RECIPES_UPDATE_FAIL";
